---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    count_threshold: 2
    checks:
      Similar code:
        enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
  eslint:
    enabled: true
    config:
      config: "./.eslintrc"
    checks:
      import/extensions:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
