sudo: required
language: node_js
node_js:
  - "7"

before_script:
  - "curl https://install.meteor.com | /bin/sh"
script:
  - "meteor add dispatch:mocha"
  - "meteor test --once --driver-package dispatch:mocha"
